# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Nilesh Somani
tagline:          'Software Engineer'
description:      'Software Engineer @ <a href="https://pavilion.io/">Pavilion</a>.<br> Linux kernel driver and file system developer.<br>Computer Science graduate from <a href="https://www.cs.stonybrook.edu/">Stony Brook University</a>.'
url:              https://nileshsomani.com
#baseurl:          '/hydeout'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Nilesh Somani'
  url:            https://nileshsomani.com

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
